global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter_monitoring"
    static_configs:
      - targets: ["nodeexporter:9100"]
